[WIP] Unified Browser Transport
uport-project/uport-transports pull request #53
Opened 2019-05-20 13:53 UTC by mi-xu

2019-05-20 22:42 UTC, mi-xu commented
Any feedback on how the tests are described would be appreciated.

2019-06-12 04:06 UTC, localredhead requested changes
I think this looks good!

The tests are very clear to me and in terms of structure/layout and general best practices I think it's :100: 

Great work!  My only feedback would be that the reference docs should have frontmatter and it should be generated so it can be published to the developer site.  That being said - I'm in favor of publishing this to an alpha or next tag so it can be integrated and a round of feedback while the documentation part is sorted.

2019-06-12 04:06 UTC, localredhead commented on docs/reference/BrowserTransport.md
> +
Is this file generated from code?  It should have frontmatter

2019-06-12 04:06 UTC, localredhead commented on package.json
> +  "version": "0.2.7-dev.4",
:+1: I'd be in support of publishing this as an alpha or next tag

2019-06-12 04:32 UTC, localredhead requested changes
Can you add a link to the running demo to the README ?

2019-06-12 18:18 UTC, localredhead approved these changes
Looks great.  :shipit:

2019-06-12 18:18 UTC, localredhead commented on README.md
> +
:+1:

2019-06-12 18:52 UTC, merged